# Generated by Django 4.2.10 on 2025-08-15 11:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Coupon Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Value')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Order Amount')),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Discount Amount')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used', null=True, verbose_name='Usage Limit')),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, help_text='Maximum number of times a user can use this coupon', null=True, verbose_name='Usage Limit Per User')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Used Count')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('first_time_customers_only', models.BooleanField(default=False, verbose_name='First Time Customers Only')),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='applicable_coupons', to='products.category', verbose_name='Applicable Categories')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='applicable_coupons', to='products.product', verbose_name='Applicable Products')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Promotion Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('promotion_type', models.CharField(choices=[('sale', 'Sale'), ('bogo', 'Buy One Get One'), ('bundle', 'Bundle Offer'), ('flash_sale', 'Flash Sale'), ('clearance', 'Clearance'), ('new_arrival', 'New Arrival')], default='sale', max_length=20, verbose_name='Promotion Type')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('banner_image', models.ImageField(blank=True, upload_to='promotions/%Y/%m/', verbose_name='Banner Image')),
                ('banner_text', models.CharField(blank=True, max_length=255, verbose_name='Banner Text')),
                ('highlight_color', models.CharField(blank=True, max_length=20, verbose_name='Highlight Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='products.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Program Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('referrer_reward_points', models.PositiveIntegerField(default=100, verbose_name='Referrer Reward Points')),
                ('referee_reward_points', models.PositiveIntegerField(default=50, verbose_name='Referee Reward Points')),
                ('referee_discount_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Referee Discount Percentage')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Referral Program',
                'verbose_name_plural': 'Referral Programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides promotion discount if set', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount price', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Price')),
                ('buy_quantity', models.PositiveIntegerField(default=1, verbose_name='Buy Quantity')),
                ('get_quantity', models.PositiveIntegerField(default=0, verbose_name='Get Quantity')),
                ('get_discount_percentage', models.DecimalField(decimal_places=2, default=100, help_text='Discount for the free/discounted item in BOGO offers', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Get Item Discount Percentage')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_promotions', to='products.product', verbose_name='Product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_products', to='promotions.promotion', verbose_name='Promotion')),
            ],
            options={
                'verbose_name': 'Promotion Product',
                'verbose_name_plural': 'Promotion Products',
                'ordering': ['display_order'],
                'unique_together': {('promotion', 'product')},
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(related_name='promotions', through='promotions.PromotionProduct', to='products.product', verbose_name='Products'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Amount')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Used At')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.coupon', verbose_name='Coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardPointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(verbose_name='Points')),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('adjusted', 'Adjusted')], max_length=10, verbose_name='Transaction Type')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reward Point Transaction',
                'verbose_name_plural': 'Reward Point Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='promotions__user_id_296e15_idx'), models.Index(fields=['transaction_type'], name='promotions__transac_2fa35c_idx'), models.Index(fields=['created_at'], name='promotions__created_caacca_idx')],
            },
        ),
        migrations.CreateModel(
            name='RewardPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_balance', models.PositiveIntegerField(default=0, verbose_name='Points Balance')),
                ('lifetime_points', models.PositiveIntegerField(default=0, verbose_name='Lifetime Points')),
                ('last_activity_date', models.DateTimeField(auto_now=True, verbose_name='Last Activity Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_points', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reward Point',
                'verbose_name_plural': 'Reward Points',
                'indexes': [models.Index(fields=['user'], name='promotions__user_id_56a781_idx'), models.Index(fields=['points_balance'], name='promotions__points__c8c0bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referee_email', models.EmailField(max_length=254, verbose_name='Referee Email')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('expired', 'Expired')], default='pending', max_length=10, verbose_name='Status')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Referral Code')),
                ('referred_at', models.DateTimeField(auto_now_add=True, verbose_name='Referred At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='promotions.referralprogram', verbose_name='Referral Program')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to=settings.AUTH_USER_MODEL, verbose_name='Referee')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Referrer')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-referred_at'],
                'indexes': [models.Index(fields=['referrer'], name='promotions__referre_aa611d_idx'), models.Index(fields=['referee'], name='promotions__referee_950cd9_idx'), models.Index(fields=['code'], name='promotions__code_c5eb8b_idx'), models.Index(fields=['status'], name='promotions__status_e592e3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['promotion_type'], name='promotions__promoti_f59ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active'], name='promotions__is_acti_fc6f30_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='promotions__start_d_283aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon'], name='promotions__coupon__a36532_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user'], name='promotions__user_id_2b7239_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['order'], name='promotions__order_i_5a0fd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'order')},
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='promotions__code_acae7b_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='promotions__is_acti_8daf39_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_until'], name='promotions__valid_f_d8a470_idx'),
        ),
    ]
