# Generated by Django 6.0.5 on 2026-05-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'verbose_name': 'کوپن', 'verbose_name_plural': 'کوپن\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='couponusage',
            options={'ordering': ['-used_at'], 'verbose_name': 'استفاده از کوپن', 'verbose_name_plural': 'استفاده\u200cهای کوپن'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_date'], 'verbose_name': 'تبلیغات', 'verbose_name_plural': 'تبلیغات'},
        ),
        migrations.AlterModelOptions(
            name='promotionproduct',
            options={'ordering': ['display_order'], 'verbose_name': 'محصول تبلیغاتی', 'verbose_name_plural': 'محصولات تبلیغاتی'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-referred_at'], 'verbose_name': 'ارجاع', 'verbose_name_plural': 'ارجاع\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='referralprogram',
            options={'ordering': ['-created_at'], 'verbose_name': 'برنامه ارجاع', 'verbose_name_plural': 'برنامه\u200cهای ارجاع'},
        ),
        migrations.AlterModelOptions(
            name='rewardpoint',
            options={'verbose_name': 'امتیاز جایزه', 'verbose_name_plural': 'امتیازات جایزه'},
        ),
        migrations.AlterModelOptions(
            name='rewardpointtransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش امتیاز', 'verbose_name_plural': 'تراکنش\u200cهای امتیاز'},
        ),
    ]
