# Generated by Django 6.0.5 on 2026-05-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='paymentdispute',
            options={'ordering': ['-created_at'], 'verbose_name': 'اختلاف پرداخت', 'verbose_name_plural': 'اختلافات پرداخت'},
        ),
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'ordering': ['name'], 'verbose_name': 'درگاه پرداخت', 'verbose_name_plural': 'درگاه\u200cهای پرداخت'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'verbose_name': 'روش پرداخت', 'verbose_name_plural': 'روش\u200cهای پرداخت'},
        ),
        migrations.AlterModelOptions(
            name='paymentrefund',
            options={'ordering': ['-created_at'], 'verbose_name': 'بازپرداخت', 'verbose_name_plural': 'بازپرداخت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='paymentwebhook',
            options={'ordering': ['-created_at'], 'verbose_name': 'وب\u200cهوک پرداخت', 'verbose_name_plural': 'وب\u200cهوک\u200cهای پرداخت'},
        ),
        migrations.AlterModelOptions(
            name='savedpaymentmethod',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'روش پرداخت ذخیره شده', 'verbose_name_plural': 'روش\u200cهای پرداخت ذخیره شده'},
        ),
    ]
