# Generated by Django 6.0.5 on 2026-05-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیام تماس', 'verbose_name_plural': 'پیام\u200cهای تماس'},
        ),
        migrations.AlterModelOptions(
            name='contactreply',
            options={'ordering': ['created_at'], 'verbose_name': 'پاسخ پیام تماس', 'verbose_name_plural': 'پاسخ\u200cهای پیام تماس'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category', 'display_order', 'question'], 'verbose_name': 'سوال متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AlterModelOptions(
            name='knowledgebasearticle',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'مقاله دانشنامه', 'verbose_name_plural': 'مقالات دانشنامه'},
        ),
        migrations.AlterModelOptions(
            name='knowledgebasecategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'دسته دانشنامه', 'verbose_name_plural': 'دسته\u200cهای دانشنامه'},
        ),
        migrations.AlterModelOptions(
            name='supportcategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'دسته پشتیبانی', 'verbose_name_plural': 'دسته\u200cهای پشتیبانی'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'تیکت پشتیبانی', 'verbose_name_plural': 'تیکت\u200cهای پشتیبانی'},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'ordering': ['created_at'], 'verbose_name': 'پیوست تیکت', 'verbose_name_plural': 'پیوست\u200cهای تیکت'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'پیام تیکت', 'verbose_name_plural': 'پیام\u200cهای تیکت'},
        ),
    ]
