# Generated by Django 6.0.5 on 2026-05-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'دسته بلاگ', 'verbose_name_plural': 'دسته\u200cهای بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at'], 'verbose_name': 'پست بلاگ', 'verbose_name_plural': 'پست\u200cهای بلاگ'},
        ),
    ]
