# Generated by Django 4.2.10 on 2025-08-15 11:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField(verbose_name='Answer')),
                ('is_staff_answer', models.BooleanField(default=False, verbose_name='Staff Answer')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonymous')),
                ('helpful_votes', models.PositiveIntegerField(default=0, verbose_name='Helpful Votes')),
                ('unhelpful_votes', models.PositiveIntegerField(default=0, verbose_name='Unhelpful Votes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Approved')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['-is_staff_answer', '-helpful_votes', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Verified Purchase')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonymous')),
                ('helpful_votes', models.PositiveIntegerField(default=0, verbose_name='Helpful Votes')),
                ('unhelpful_votes', models.PositiveIntegerField(default=0, verbose_name='Unhelpful Votes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Moderated At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Moderated By')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.orderitem', verbose_name='Order Item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='reviews/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'Review Image',
                'verbose_name_plural': 'Review Images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='Question')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('answered', 'Answered'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonymous')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Moderated At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_questions', to=settings.AUTH_USER_MODEL, verbose_name='Moderated By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='products.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('helpful', 'Helpful'), ('unhelpful', 'Unhelpful')], max_length=10, verbose_name='Vote')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.answer', verbose_name='Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Answer Vote',
                'verbose_name_plural': 'Answer Votes',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reviews.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('helpful', 'Helpful'), ('unhelpful', 'Unhelpful')], max_length=10, verbose_name='Vote')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.review', verbose_name='Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review Vote',
                'verbose_name_plural': 'Review Votes',
                'indexes': [models.Index(fields=['review'], name='reviews_rev_review__163e87_idx'), models.Index(fields=['user'], name='reviews_rev_user_id_8bdf16_idx'), models.Index(fields=['vote'], name='reviews_rev_vote_05386c_idx')],
                'unique_together': {('review', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Content')),
                ('is_staff_response', models.BooleanField(default=False, verbose_name='Staff Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Approved')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review', verbose_name='Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review Comment',
                'verbose_name_plural': 'Review Comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['review'], name='reviews_rev_review__7967d1_idx'), models.Index(fields=['user'], name='reviews_rev_user_id_6a0169_idx'), models.Index(fields=['is_staff_response'], name='reviews_rev_is_staf_e09c2e_idx'), models.Index(fields=['created_at'], name='reviews_rev_created_e1dbe7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='reviews_rev_product_a9ee0d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='reviews_rev_user_id_a65d48_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='reviews_rev_status_5966f7_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='reviews_rev_created_bdcc91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['product'], name='reviews_que_product_41f7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['user'], name='reviews_que_user_id_1e2ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status'], name='reviews_que_status_8b7179_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='reviews_que_created_d784d6_idx'),
        ),
        migrations.AddIndex(
            model_name='answervote',
            index=models.Index(fields=['answer'], name='reviews_ans_answer__6cdd62_idx'),
        ),
        migrations.AddIndex(
            model_name='answervote',
            index=models.Index(fields=['user'], name='reviews_ans_user_id_a839dc_idx'),
        ),
        migrations.AddIndex(
            model_name='answervote',
            index=models.Index(fields=['vote'], name='reviews_ans_vote_439987_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answervote',
            unique_together={('answer', 'user')},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='reviews_ans_questio_467742_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['user'], name='reviews_ans_user_id_fc3ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_staff_answer'], name='reviews_ans_is_staf_a9566c_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['created_at'], name='reviews_ans_created_15e068_idx'),
        ),
    ]
