# Generated by Django 6.0.5 on 2026-05-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-is_staff_answer', '-helpful_votes', 'created_at'], 'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='answervote',
            options={'verbose_name': 'رأی پاسخ', 'verbose_name_plural': 'آراء پاسخ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'پرسش', 'verbose_name_plural': 'پرسش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='reviewcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'نظر روی نظر', 'verbose_name_plural': 'نظرات روی نظر'},
        ),
        migrations.AlterModelOptions(
            name='reviewimage',
            options={'ordering': ['created_at'], 'verbose_name': 'تصویر نظر', 'verbose_name_plural': 'تصاویر نظرات'},
        ),
        migrations.AlterModelOptions(
            name='reviewvote',
            options={'verbose_name': 'رأی نظر', 'verbose_name_plural': 'آراء نظرات'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
