# Generated by Django 6.0.5 on 2026-05-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_answer_options_alter_answervote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Session Key'),
        ),
    ]
