# Generated by Django 6.0.5 on 2026-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewvote',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Session Key'),
        ),
    ]
