# Generated by Django 6.0.5 on 2026-05-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_reviewvote_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
