# Generated by Django 4.2.10 on 2026-05-06 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prescription_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prescription Verified At'),
        ),
        migrations.AddField(
            model_name='cart',
            name='prescription_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
    ]
