# Generated by Django 4.2.10 on 2026-05-06 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_cart_prescription_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prescription_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_order_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
    ]
