# Generated by Django 6.0.5 on 2026-05-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cart_prescription_verified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated_at'], 'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبدهای خرید'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-added_at'], 'verbose_name': 'آیتم سبد خرید', 'verbose_name_plural': 'آیتم\u200cهای سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['product_name'], 'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم\u200cهای سفارش'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-requested_at'], 'verbose_name': 'بازپرداخت سفارش', 'verbose_name_plural': 'بازپرداخت\u200cهای سفارش'},
        ),
        migrations.AlterModelOptions(
            name='refunditem',
            options={'verbose_name': 'آیتم بازپرداخت', 'verbose_name_plural': 'آیتم\u200cهای بازپرداخت'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'مرسوله', 'verbose_name_plural': 'مرسولات'},
        ),
        migrations.AlterModelOptions(
            name='shipmentitem',
            options={'verbose_name': 'آیتم مرسوله', 'verbose_name_plural': 'آیتم\u200cهای مرسوله'},
        ),
    ]
