# Generated by Django 4.2.10 on 2026-05-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_order_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Maximum quantity a user can order in a single purchase. 0 = unlimited.', verbose_name='Maximum Order Quantity'),
        ),
    ]
