# Generated by Django 6.0.5 on 2026-05-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_max_order_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['expiry_date'], 'verbose_name': 'دسته (بچ)', 'verbose_name_plural': 'دسته\u200cها (بچ\u200cها)'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'تولیدکننده', 'verbose_name_plural': 'تولیدکنندگان'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'جزئیات دارو', 'verbose_name_plural': 'جزئیات داروها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصول'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'ordering': ['name'], 'verbose_name': 'برچسب محصول', 'verbose_name_plural': 'برچسب\u200cهای محصول'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['name'], 'verbose_name': 'تنوع محصول', 'verbose_name_plural': 'تنوع\u200cهای محصول'},
        ),
    ]
